# 自动生成, 勿手改: SoftFloat-3e FAST_INT64 精确源集
# 取自 build/Linux-x86_64-GCC 的 'make -Bn' (= source/*.c + source/8086-SSE/*.c, 302 个);
# 与 x86_64/loongarch64 原生一致, i386 用同一集 + 可移植 platform.h(INT128 关) 亦通过。
SF_SRCS_COMMON := \
 third_party/softfloat-3e/source/8086-SSE/extF80M_isSignalingNaN.c \
 third_party/softfloat-3e/source/8086-SSE/f128M_isSignalingNaN.c \
 third_party/softfloat-3e/source/8086-SSE/s_commonNaNToExtF80UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_commonNaNToF128UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_commonNaNToF16UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_commonNaNToF32UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_commonNaNToF64UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_extF80UIToCommonNaN.c \
 third_party/softfloat-3e/source/8086-SSE/s_f128UIToCommonNaN.c \
 third_party/softfloat-3e/source/8086-SSE/s_f16UIToCommonNaN.c \
 third_party/softfloat-3e/source/8086-SSE/s_f32UIToCommonNaN.c \
 third_party/softfloat-3e/source/8086-SSE/s_f64UIToCommonNaN.c \
 third_party/softfloat-3e/source/8086-SSE/softfloat_raiseFlags.c \
 third_party/softfloat-3e/source/8086-SSE/s_propagateNaNExtF80UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_propagateNaNF128UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_propagateNaNF16UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_propagateNaNF32UI.c \
 third_party/softfloat-3e/source/8086-SSE/s_propagateNaNF64UI.c \
 third_party/softfloat-3e/source/extF80_add.c \
 third_party/softfloat-3e/source/extF80_div.c \
 third_party/softfloat-3e/source/extF80_eq.c \
 third_party/softfloat-3e/source/extF80_eq_signaling.c \
 third_party/softfloat-3e/source/extF80_isSignalingNaN.c \
 third_party/softfloat-3e/source/extF80_le.c \
 third_party/softfloat-3e/source/extF80_le_quiet.c \
 third_party/softfloat-3e/source/extF80_lt.c \
 third_party/softfloat-3e/source/extF80_lt_quiet.c \
 third_party/softfloat-3e/source/extF80M_add.c \
 third_party/softfloat-3e/source/extF80M_div.c \
 third_party/softfloat-3e/source/extF80M_eq.c \
 third_party/softfloat-3e/source/extF80M_eq_signaling.c \
 third_party/softfloat-3e/source/extF80M_le.c \
 third_party/softfloat-3e/source/extF80M_le_quiet.c \
 third_party/softfloat-3e/source/extF80M_lt.c \
 third_party/softfloat-3e/source/extF80M_lt_quiet.c \
 third_party/softfloat-3e/source/extF80M_mul.c \
 third_party/softfloat-3e/source/extF80M_rem.c \
 third_party/softfloat-3e/source/extF80M_roundToInt.c \
 third_party/softfloat-3e/source/extF80M_sqrt.c \
 third_party/softfloat-3e/source/extF80M_sub.c \
 third_party/softfloat-3e/source/extF80M_to_f128M.c \
 third_party/softfloat-3e/source/extF80M_to_f16.c \
 third_party/softfloat-3e/source/extF80M_to_f32.c \
 third_party/softfloat-3e/source/extF80M_to_f64.c \
 third_party/softfloat-3e/source/extF80M_to_i32.c \
 third_party/softfloat-3e/source/extF80M_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/extF80M_to_i64.c \
 third_party/softfloat-3e/source/extF80M_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/extF80M_to_ui32.c \
 third_party/softfloat-3e/source/extF80M_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/extF80M_to_ui64.c \
 third_party/softfloat-3e/source/extF80M_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/extF80_mul.c \
 third_party/softfloat-3e/source/extF80_rem.c \
 third_party/softfloat-3e/source/extF80_roundToInt.c \
 third_party/softfloat-3e/source/extF80_sqrt.c \
 third_party/softfloat-3e/source/extF80_sub.c \
 third_party/softfloat-3e/source/extF80_to_f128.c \
 third_party/softfloat-3e/source/extF80_to_f16.c \
 third_party/softfloat-3e/source/extF80_to_f32.c \
 third_party/softfloat-3e/source/extF80_to_f64.c \
 third_party/softfloat-3e/source/extF80_to_i32.c \
 third_party/softfloat-3e/source/extF80_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/extF80_to_i64.c \
 third_party/softfloat-3e/source/extF80_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/extF80_to_ui32.c \
 third_party/softfloat-3e/source/extF80_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/extF80_to_ui64.c \
 third_party/softfloat-3e/source/extF80_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/f128_add.c \
 third_party/softfloat-3e/source/f128_div.c \
 third_party/softfloat-3e/source/f128_eq.c \
 third_party/softfloat-3e/source/f128_eq_signaling.c \
 third_party/softfloat-3e/source/f128_isSignalingNaN.c \
 third_party/softfloat-3e/source/f128_le.c \
 third_party/softfloat-3e/source/f128_le_quiet.c \
 third_party/softfloat-3e/source/f128_lt.c \
 third_party/softfloat-3e/source/f128_lt_quiet.c \
 third_party/softfloat-3e/source/f128M_add.c \
 third_party/softfloat-3e/source/f128M_div.c \
 third_party/softfloat-3e/source/f128M_eq.c \
 third_party/softfloat-3e/source/f128M_eq_signaling.c \
 third_party/softfloat-3e/source/f128M_le.c \
 third_party/softfloat-3e/source/f128M_le_quiet.c \
 third_party/softfloat-3e/source/f128M_lt.c \
 third_party/softfloat-3e/source/f128M_lt_quiet.c \
 third_party/softfloat-3e/source/f128M_mulAdd.c \
 third_party/softfloat-3e/source/f128M_mul.c \
 third_party/softfloat-3e/source/f128M_rem.c \
 third_party/softfloat-3e/source/f128M_roundToInt.c \
 third_party/softfloat-3e/source/f128M_sqrt.c \
 third_party/softfloat-3e/source/f128M_sub.c \
 third_party/softfloat-3e/source/f128M_to_extF80M.c \
 third_party/softfloat-3e/source/f128M_to_f16.c \
 third_party/softfloat-3e/source/f128M_to_f32.c \
 third_party/softfloat-3e/source/f128M_to_f64.c \
 third_party/softfloat-3e/source/f128M_to_i32.c \
 third_party/softfloat-3e/source/f128M_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/f128M_to_i64.c \
 third_party/softfloat-3e/source/f128M_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/f128M_to_ui32.c \
 third_party/softfloat-3e/source/f128M_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/f128M_to_ui64.c \
 third_party/softfloat-3e/source/f128M_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/f128_mulAdd.c \
 third_party/softfloat-3e/source/f128_mul.c \
 third_party/softfloat-3e/source/f128_rem.c \
 third_party/softfloat-3e/source/f128_roundToInt.c \
 third_party/softfloat-3e/source/f128_sqrt.c \
 third_party/softfloat-3e/source/f128_sub.c \
 third_party/softfloat-3e/source/f128_to_extF80.c \
 third_party/softfloat-3e/source/f128_to_f16.c \
 third_party/softfloat-3e/source/f128_to_f32.c \
 third_party/softfloat-3e/source/f128_to_f64.c \
 third_party/softfloat-3e/source/f128_to_i32.c \
 third_party/softfloat-3e/source/f128_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/f128_to_i64.c \
 third_party/softfloat-3e/source/f128_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/f128_to_ui32.c \
 third_party/softfloat-3e/source/f128_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/f128_to_ui64.c \
 third_party/softfloat-3e/source/f128_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/f16_add.c \
 third_party/softfloat-3e/source/f16_div.c \
 third_party/softfloat-3e/source/f16_eq.c \
 third_party/softfloat-3e/source/f16_eq_signaling.c \
 third_party/softfloat-3e/source/f16_isSignalingNaN.c \
 third_party/softfloat-3e/source/f16_le.c \
 third_party/softfloat-3e/source/f16_le_quiet.c \
 third_party/softfloat-3e/source/f16_lt.c \
 third_party/softfloat-3e/source/f16_lt_quiet.c \
 third_party/softfloat-3e/source/f16_mulAdd.c \
 third_party/softfloat-3e/source/f16_mul.c \
 third_party/softfloat-3e/source/f16_rem.c \
 third_party/softfloat-3e/source/f16_roundToInt.c \
 third_party/softfloat-3e/source/f16_sqrt.c \
 third_party/softfloat-3e/source/f16_sub.c \
 third_party/softfloat-3e/source/f16_to_extF80.c \
 third_party/softfloat-3e/source/f16_to_extF80M.c \
 third_party/softfloat-3e/source/f16_to_f128.c \
 third_party/softfloat-3e/source/f16_to_f128M.c \
 third_party/softfloat-3e/source/f16_to_f32.c \
 third_party/softfloat-3e/source/f16_to_f64.c \
 third_party/softfloat-3e/source/f16_to_i32.c \
 third_party/softfloat-3e/source/f16_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/f16_to_i64.c \
 third_party/softfloat-3e/source/f16_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/f16_to_ui32.c \
 third_party/softfloat-3e/source/f16_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/f16_to_ui64.c \
 third_party/softfloat-3e/source/f16_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/f32_add.c \
 third_party/softfloat-3e/source/f32_div.c \
 third_party/softfloat-3e/source/f32_eq.c \
 third_party/softfloat-3e/source/f32_eq_signaling.c \
 third_party/softfloat-3e/source/f32_isSignalingNaN.c \
 third_party/softfloat-3e/source/f32_le.c \
 third_party/softfloat-3e/source/f32_le_quiet.c \
 third_party/softfloat-3e/source/f32_lt.c \
 third_party/softfloat-3e/source/f32_lt_quiet.c \
 third_party/softfloat-3e/source/f32_mulAdd.c \
 third_party/softfloat-3e/source/f32_mul.c \
 third_party/softfloat-3e/source/f32_rem.c \
 third_party/softfloat-3e/source/f32_roundToInt.c \
 third_party/softfloat-3e/source/f32_sqrt.c \
 third_party/softfloat-3e/source/f32_sub.c \
 third_party/softfloat-3e/source/f32_to_extF80.c \
 third_party/softfloat-3e/source/f32_to_extF80M.c \
 third_party/softfloat-3e/source/f32_to_f128.c \
 third_party/softfloat-3e/source/f32_to_f128M.c \
 third_party/softfloat-3e/source/f32_to_f16.c \
 third_party/softfloat-3e/source/f32_to_f64.c \
 third_party/softfloat-3e/source/f32_to_i32.c \
 third_party/softfloat-3e/source/f32_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/f32_to_i64.c \
 third_party/softfloat-3e/source/f32_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/f32_to_ui32.c \
 third_party/softfloat-3e/source/f32_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/f32_to_ui64.c \
 third_party/softfloat-3e/source/f32_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/f64_add.c \
 third_party/softfloat-3e/source/f64_div.c \
 third_party/softfloat-3e/source/f64_eq.c \
 third_party/softfloat-3e/source/f64_eq_signaling.c \
 third_party/softfloat-3e/source/f64_isSignalingNaN.c \
 third_party/softfloat-3e/source/f64_le.c \
 third_party/softfloat-3e/source/f64_le_quiet.c \
 third_party/softfloat-3e/source/f64_lt.c \
 third_party/softfloat-3e/source/f64_lt_quiet.c \
 third_party/softfloat-3e/source/f64_mulAdd.c \
 third_party/softfloat-3e/source/f64_mul.c \
 third_party/softfloat-3e/source/f64_rem.c \
 third_party/softfloat-3e/source/f64_roundToInt.c \
 third_party/softfloat-3e/source/f64_sqrt.c \
 third_party/softfloat-3e/source/f64_sub.c \
 third_party/softfloat-3e/source/f64_to_extF80.c \
 third_party/softfloat-3e/source/f64_to_extF80M.c \
 third_party/softfloat-3e/source/f64_to_f128.c \
 third_party/softfloat-3e/source/f64_to_f128M.c \
 third_party/softfloat-3e/source/f64_to_f16.c \
 third_party/softfloat-3e/source/f64_to_f32.c \
 third_party/softfloat-3e/source/f64_to_i32.c \
 third_party/softfloat-3e/source/f64_to_i32_r_minMag.c \
 third_party/softfloat-3e/source/f64_to_i64.c \
 third_party/softfloat-3e/source/f64_to_i64_r_minMag.c \
 third_party/softfloat-3e/source/f64_to_ui32.c \
 third_party/softfloat-3e/source/f64_to_ui32_r_minMag.c \
 third_party/softfloat-3e/source/f64_to_ui64.c \
 third_party/softfloat-3e/source/f64_to_ui64_r_minMag.c \
 third_party/softfloat-3e/source/i32_to_extF80.c \
 third_party/softfloat-3e/source/i32_to_extF80M.c \
 third_party/softfloat-3e/source/i32_to_f128.c \
 third_party/softfloat-3e/source/i32_to_f128M.c \
 third_party/softfloat-3e/source/i32_to_f16.c \
 third_party/softfloat-3e/source/i32_to_f32.c \
 third_party/softfloat-3e/source/i32_to_f64.c \
 third_party/softfloat-3e/source/i64_to_extF80.c \
 third_party/softfloat-3e/source/i64_to_extF80M.c \
 third_party/softfloat-3e/source/i64_to_f128.c \
 third_party/softfloat-3e/source/i64_to_f128M.c \
 third_party/softfloat-3e/source/i64_to_f16.c \
 third_party/softfloat-3e/source/i64_to_f32.c \
 third_party/softfloat-3e/source/i64_to_f64.c \
 third_party/softfloat-3e/source/s_add128.c \
 third_party/softfloat-3e/source/s_add256M.c \
 third_party/softfloat-3e/source/s_addMagsExtF80.c \
 third_party/softfloat-3e/source/s_addMagsF128.c \
 third_party/softfloat-3e/source/s_addMagsF16.c \
 third_party/softfloat-3e/source/s_addMagsF32.c \
 third_party/softfloat-3e/source/s_addMagsF64.c \
 third_party/softfloat-3e/source/s_approxRecip_1Ks.c \
 third_party/softfloat-3e/source/s_approxRecip32_1.c \
 third_party/softfloat-3e/source/s_approxRecipSqrt_1Ks.c \
 third_party/softfloat-3e/source/s_approxRecipSqrt32_1.c \
 third_party/softfloat-3e/source/s_countLeadingZeros16.c \
 third_party/softfloat-3e/source/s_countLeadingZeros32.c \
 third_party/softfloat-3e/source/s_countLeadingZeros64.c \
 third_party/softfloat-3e/source/s_countLeadingZeros8.c \
 third_party/softfloat-3e/source/s_eq128.c \
 third_party/softfloat-3e/source/s_le128.c \
 third_party/softfloat-3e/source/s_lt128.c \
 third_party/softfloat-3e/source/s_mul128By32.c \
 third_party/softfloat-3e/source/s_mul128To256M.c \
 third_party/softfloat-3e/source/s_mul64ByShifted32To128.c \
 third_party/softfloat-3e/source/s_mul64To128.c \
 third_party/softfloat-3e/source/s_mulAddF128.c \
 third_party/softfloat-3e/source/s_mulAddF16.c \
 third_party/softfloat-3e/source/s_mulAddF32.c \
 third_party/softfloat-3e/source/s_mulAddF64.c \
 third_party/softfloat-3e/source/s_normRoundPackToExtF80.c \
 third_party/softfloat-3e/source/s_normRoundPackToF128.c \
 third_party/softfloat-3e/source/s_normRoundPackToF16.c \
 third_party/softfloat-3e/source/s_normRoundPackToF32.c \
 third_party/softfloat-3e/source/s_normRoundPackToF64.c \
 third_party/softfloat-3e/source/s_normSubnormalExtF80Sig.c \
 third_party/softfloat-3e/source/s_normSubnormalF128Sig.c \
 third_party/softfloat-3e/source/s_normSubnormalF16Sig.c \
 third_party/softfloat-3e/source/s_normSubnormalF32Sig.c \
 third_party/softfloat-3e/source/s_normSubnormalF64Sig.c \
 third_party/softfloat-3e/source/softfloat_state.c \
 third_party/softfloat-3e/source/s_roundPackToExtF80.c \
 third_party/softfloat-3e/source/s_roundPackToF128.c \
 third_party/softfloat-3e/source/s_roundPackToF16.c \
 third_party/softfloat-3e/source/s_roundPackToF32.c \
 third_party/softfloat-3e/source/s_roundPackToF64.c \
 third_party/softfloat-3e/source/s_roundToI32.c \
 third_party/softfloat-3e/source/s_roundToI64.c \
 third_party/softfloat-3e/source/s_roundToUI32.c \
 third_party/softfloat-3e/source/s_roundToUI64.c \
 third_party/softfloat-3e/source/s_shiftRightJam128.c \
 third_party/softfloat-3e/source/s_shiftRightJam128Extra.c \
 third_party/softfloat-3e/source/s_shiftRightJam256M.c \
 third_party/softfloat-3e/source/s_shiftRightJam32.c \
 third_party/softfloat-3e/source/s_shiftRightJam64.c \
 third_party/softfloat-3e/source/s_shiftRightJam64Extra.c \
 third_party/softfloat-3e/source/s_shortShiftLeft128.c \
 third_party/softfloat-3e/source/s_shortShiftRight128.c \
 third_party/softfloat-3e/source/s_shortShiftRightJam128.c \
 third_party/softfloat-3e/source/s_shortShiftRightJam128Extra.c \
 third_party/softfloat-3e/source/s_shortShiftRightJam64.c \
 third_party/softfloat-3e/source/s_shortShiftRightJam64Extra.c \
 third_party/softfloat-3e/source/s_sub128.c \
 third_party/softfloat-3e/source/s_sub256M.c \
 third_party/softfloat-3e/source/s_subMagsExtF80.c \
 third_party/softfloat-3e/source/s_subMagsF128.c \
 third_party/softfloat-3e/source/s_subMagsF16.c \
 third_party/softfloat-3e/source/s_subMagsF32.c \
 third_party/softfloat-3e/source/s_subMagsF64.c \
 third_party/softfloat-3e/source/ui32_to_extF80.c \
 third_party/softfloat-3e/source/ui32_to_extF80M.c \
 third_party/softfloat-3e/source/ui32_to_f128.c \
 third_party/softfloat-3e/source/ui32_to_f128M.c \
 third_party/softfloat-3e/source/ui32_to_f16.c \
 third_party/softfloat-3e/source/ui32_to_f32.c \
 third_party/softfloat-3e/source/ui32_to_f64.c \
 third_party/softfloat-3e/source/ui64_to_extF80.c \
 third_party/softfloat-3e/source/ui64_to_extF80M.c \
 third_party/softfloat-3e/source/ui64_to_f128.c \
 third_party/softfloat-3e/source/ui64_to_f128M.c \
 third_party/softfloat-3e/source/ui64_to_f16.c \
 third_party/softfloat-3e/source/ui64_to_f32.c \
 third_party/softfloat-3e/source/ui64_to_f64.c
